# Generated by Django 3.0.3 on 2020-07-04 07:10

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('india', 'INDIA')], default='india', max_length=20)),
                ('city', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Pune', 'Pune'), ('Nagpur', 'Nagpur'), ('Delhi', 'Delhi'), ('Bangalore', 'Bangalore'), ('Hyderabad', 'Hyderabad'), ('Ahmedabad', 'Ahmedabad'), ('Chennai', 'Chennai'), ('Kolkata', 'Kolkata'), ('Surat', 'Surat'), ('Jaipur', 'Jaipur'), ('Lucknow', 'Lucknow'), ('Bhopal', 'Bhopal'), ('Indore', 'Indore'), ('Patna', 'Patna'), ('Srinagar', 'Srinagar'), ('Ranchi', 'Ranchi'), ('Raipur', 'Raipur'), ('Chandigarh', 'Chandigarh'), ('Bhubaneswar', 'Bhubaneswar'), ('Dehradun', 'Dehradun'), ('Jammu', 'Jammu'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Shimla', 'Shimla')], default='Mumbai', max_length=20)),
                ('name', models.CharField(db_index=True, max_length=10)),
                ('description', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_category', to='api.Category')),
                ('job_offered_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offered_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Applicant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_name', to='api.Job')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_applied_by', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
